name: sreu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.20
  - scipy=1.6
  - astropy=4.2
  - sunpy=3.0
  - aiapy=0.5
  - matplotlib=3.4
  - heliopy=0.13
  - plasmapy=0.6
  - jupyter
  - pandas=1.2
  - xarray=0.17
  - pytest=6.2
  - pytest-astropy
  - pip
  - pip:
    - mpmath
    - lmfit
    - astroquery
    - jplephem
